name: Test Network Building

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
      
      - name: Install additional dependencies
        run: |
          pip install python-louvain bioservices mygene zeep requests
          
      - name: Run demo network script
        run: |
          mkdir -p output
          python examples/demo_network.py --organism mouse
        env:
          PYTHONUNBUFFERED: 1
          
      - name: Upload network visualization
        uses: actions/upload-artifact@v3
        with:
          name: network-visualization
          path: output/
          retention-days: 7
      
      - name: Test build script with debug mode
        run: |
          python maintenance/build_networks.py --output-dir test_data --organisms mouse --debug
        env:
          PYTHONUNBUFFERED: 1
          
      - name: Upload test network
        uses: actions/upload-artifact@v3
        with:
          name: test-network
          path: test_data/
          retention-days: 7
          