name: Update Model Organism Networks

on:
  schedule:
    # Run every other month on the 1st at midnight
    - cron: '0 0 1 1,3,5,7,9,11 *'
  workflow_dispatch:
    inputs:
      organisms:
        description: 'Comma-separated list of organisms to build (human,mouse,yeast,ecoli)'
        required: false
        default: 'human,mouse,yeast,ecoli'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          
      - name: Build networks
        run: |
          python maintenance/build_networks.py --output-dir data
          
      - name: Commit and push updated networks
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          timestamp=$(date +"%Y-%m-%d")
          git commit -m "Update model organism networks - $timestamp" || echo "No changes to commit"
          git push
          